# Generated by Django 5.1.1 on 2024-10-10 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=150, verbose_name='Comentario')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('fecha_comentario', models.DateTimeField(auto_now=True, verbose_name='Comentado el')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modificado')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_publicacion', models.CharField(help_text='Título de la publicación.', max_length=50, verbose_name='Título')),
                ('publicacion', models.TextField(help_text='Texto de la publicación.', max_length=250, verbose_name='Texto')),
                ('imagen', models.ImageField(blank=True, default='img_default/public_default.jpg', null=True, upload_to='publicaciones', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True, verbose_name='Publicado')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modificado')),
            ],
            options={
                'ordering': ('titulo_publicacion',),
            },
        ),
    ]
